import react, { useState, useRef, useEffect } from "react";
import css from "../styles/Home.module.scss";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Rellax from "rellax";

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

import headerImg from "../public/assets/headerImg.jpg";
import middleImg from "../public/assets/middleImg.jpg";
import { icons } from "../public/assets/icons/Icons";


export default function Home() {
    gsap.registerPlugin(ScrollTrigger);


 

    const [name, setName] = useState("");
    const [mail, setMail] = useState("");
    const [message, setMessage] = useState("");
    const [span, setSpan] = useState('')


    const handleForm = e => {
        e.preventDefault()
        console.log('name', name);
        console.log('mail', mail);
        console.log('message', message);
       
        setSpan('Votre message a bien été envoyé')

        setTimeout(() => {
            setName('')
            setMail('')
            setMessage('')
            setSpan('')
        },1500)

    }

    const handleSubmit = e => {
        e.preventDefault()
    }

    const rellaxRef = useRef();

   

    useEffect(() => {
        new Rellax(rellaxRef.current, {
            speed: 0,
            center: false,
            wrapper: null,
            round: true,
            vertical: true,
            horizontal: false,
        });
    }, [rellaxRef]);

    return (
        <div className={css.globalContainer}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                {/* header */}

                <div className={css.headerContainer}>
                    <div 
                    // ref={rellaxRef}
                     className={css.imgHeader}></div>

                    {/* navbar */}

                    <div className={css.navbarContainer}>
                        <div className={css.title}>GB</div>
                        <div className={css.navbar}>
                            <button>projets.</button>
                            <button>à propos.</button>
                            <button>contact.</button>
                        </div>
                    </div>
                </div>
            </header>

            <section>
                {/* section projet */}
                <div className={css.projetContainer}>
                    <h1 className={css.projetTitle}>projets.</h1>
                    <div className={css.projetGrid}>
                        <div className={css.projetCard}>Projet 1</div>
                        <div className={css.projetCard}>Projet 2</div>
                        <div className={css.projetCard}>Projet 3</div>
                        <div className={css.projetCard}>Projet 4</div>
                        <div className={css.projetCard}>Projet 5</div>
                        <div className={css.projetCard}>Projet 6</div>
                    </div>
                </div>
            </section>
            {/* middle bar */}
            <div className={css.middleBar}>
                <div 
                // ref={rellaxRef}
                 className={css.middleImg}></div>
            </div>
            {/* a propos */}
            <section className={css.proposContainer}>
                <h1 className={css.proposTitle}>A propos.</h1>
                <p className={css.proposTxt}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem sit dolorem nisi aperiam aut mollitia nostrum a consequatur quam! Suscipit quae quam blanditiis molestiae accusamus. Dignissimos, hic, magnam repudiandae facere perspiciatis atque, qui ullam culpa suscipit numquam debitis amet quas earum odio et ea beatae sed iusto dolorem ex deserunt!</p>

                <div className={css.iconContainer}>
                    {icons.map((e) => (                       
                        <div className={css.iconItem} key={e.id}>
                            <Image
                                src={e.url}
                               width={100}
                               height={100}
                               alt={e.name}
                            />
                        </div>
                    ))}
                </div>

            </section>
            {/* bottom bar */}

            <div className={css.bottomBar}>
                <div 
                // ref={rellaxRef}
                 className={css.bottomImg}></div>
            </div>

            {/* CONTACT */}

            <div className={css.contactContainer}>
            <h1 className={css.contactTitle}>contact.</h1>
                <form 
                onSubmit={handleForm}
                className={css.form}>

                    <input 
                    onChange={(e) => setName(e.target.value)}
                    value={name}
                    className={css.inputSmall} 
                    type="text" 
                    required 
                    placeholder="Enter your name" 
                    id="name" />
                    <input 

                     onChange={(e) => setMail(e.target.value)}
                     value={mail}
                    className={css.inputSmall} 
                    type="email" 
                    required 
                    placeholder="Enter your e-mail" 
                    id="mail" />
                    <textarea 
                     onChange={(e) => setMessage(e.target.value)}
                     value={message}
                    className={css.inputBig} 
                    type="text"  
                    required 
                    placeholder="Message" 
                    id="message" />
                    <span className={css.formSpan}> {span}</span>
                    <button
                    // onSubmit={handleSubmit}
                     className={css.btnSubmit} >Submit</button>
                </form>

            </div>

        </div>
    );
}
